# These settings will be loaded if no other settings are saved.
---
simianFileOptionsDefault:
  balanceParentheses: False
  balanceSquareBrackets: False
  failOnDuplication: True
  ignoreCharacterCase: True
  ignoreCharacters: False
  ignoreCurlyBraces: False
  ignoreIdentifierCase: True
  ignoreIdentifiers: False
  ignoreLiterals: False
  ignoreModifiers: True
  ignoreNumbers: False
  ignoreStringCase: True
  ignoreStrings: False
  ignoreSubtypeNames: False
  ignoreVariableNames: False
  threshold: 2
---
# These settings will be loaded when the user saves settings and used
# until the user chooses to reset to defaults.
simianFileOptionsSaved:
  balanceParentheses: False
  balanceSquareBrackets: False
  failOnDuplication: True
  ignoreCharacterCase: True
  ignoreCharacters: False
  ignoreCurlyBraces: False
  ignoreIdentifierCase: True
  ignoreIdentifiers: False
  ignoreLiterals: False
  ignoreModifiers: True
  ignoreNumbers: False
  ignoreStringCase: True
  ignoreStrings: False
  ignoreSubtypeNames: False
  ignoreVariableNames: False
  threshold: 2
---
fileDirsSaved:
  simianWorkFileDir:
  kDiff3WorkFileDir:
