# These settings will be loaded if no other settings are saved.
simianFileOptionsDefault:
  FailOnDupl: True
  IgnoreCurlyBraces: False
  IgnoreIdent: False
  IgnoreIdentCase: True
  IgnoreLiterals: False
  IgnoreNumbers: False
  IgnoreCharacters: False
  IgnoreCharacterCase: True
  IgnoreStrings: False
  IgnoreStringCase: True
  IgnoreSubtypeNames: False
  IgnoreModifiers: True
  IgnoreVariableNames: False
  BalanceParentheses: False
  BalanceSquareBrackets: False
  Threshold: 2

# These settings will be loaded when the user saves settings and used
# until the user chooses to reset to defaults.
simianFileOptionsSaved:
  FailOnDupl:
  IgnoreCurlyBraces:
  IgnoreIdent:
  IgnoreIdentCase:
  IgnoreLiterals:
  IgnoreNumbers:
  IgnoreCharacters:
  IgnoreCharacterCase:
  IgnoreStrings:
  IgnoreStringCase:
  IgnoreSubtypeNames:
  IgnoreModifiers:
  IgnoreVariableNames:
  BalanceParentheses:
  BalanceSquareBrackets:
  Threshold:

fileDirsSaved:
  SimianWorkFileDir:
  kDiff3WorkFileDir:
